name: Pylint Check

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install pylint
      run: pip3 install pylint
    
    - name: pylint check
      run: pylint --rcfile=.pylintrc fylesdk/**/**.py
